services:
  btps-server:
    container_name: btps-server-prod
    build:
      context: .
      dockerfile: Dockerfile # Your current multi-stage file
    ports:
      - '3000:3443' # External 3000 maps to internal 3443
    env_file:
      - .env
